version: '3'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    security_opt:
      - seccomp:seccomp-chromium.json
  redis:
    image: redis:alpine
